'use client';

import React from 'react';
import Link from 'next/link';
import { useAuth } from '@/context/AuthContext';
import { 
  Sparkles, 
  TrendingUp, 
  MessageSquare, 
  ShieldAlert, 
  CloudSun, 
  ArrowRight,
  Sprout,
  UserCheck
} from 'lucide-react';

export default function Home() {
  const { user } = useAuth();

  const features = [
    {
      title: 'Gemini AI Assistant',
      desc: 'Have natural conversations about clothing, travel, farming, or leisure recommendations. Complete with voice-to-text dictation and voice speech.',
      icon: MessageSquare,
      color: 'from-purple-500 to-indigo-500'
    },
    {
      title: 'Real-Time Insights',
      desc: 'Retrieve instantly updated temperatures, air quality conditions, UV indexes, and sunrise cycles using precision location geocoding.',
      icon: CloudSun,
      color: 'from-amber-400 to-orange-500'
    },
    {
      title: 'Deep Forecast Analytics',
      desc: 'Interact with beautiful visual charts tracking temperature envelopes, rain probability cycles, and historical trends over days.',
      icon: TrendingUp,
      color: 'from-sky-400 to-blue-500'
    },
    {
      title: 'Personalized Smart Advisories',
      desc: 'Receive AI predictions on agricultural watering schedules, health risks (allergy alerts), and home energy savings advice.',
      icon: Sprout,
      color: 'from-emerald-400 to-teal-500'
    },
    {
      title: 'Real-Time Alert Center',
      desc: 'Stay informed with automated notifications on storms, harsh winds, and local safety precautions generated by our met-intelligence.',
      icon: ShieldAlert,
      color: 'from-rose-500 to-red-600'
    }
  ];

  return (
    <div className="flex flex-col items-center justify-center py-8 sm:py-16 md:py-24 relative overflow-hidden">
      {/* Decorative background ambient glows */}
      <div className="absolute top-1/4 left-1/4 w-96 h-96 bg-sky-500/10 rounded-full blur-3xl -z-10" />
      <div className="absolute bottom-1/4 right-1/4 w-96 h-96 bg-purple-500/10 rounded-full blur-3xl -z-10" />

      {/* Hero Section */}
      <div className="text-center max-w-3xl space-y-6 px-4 animate-fade-in">
        <div className="inline-flex items-center gap-1.5 px-3 py-1 rounded-full bg-white/5 border border-white/10 text-xs font-semibold text-sky-300">
          <Sparkles className="w-3.5 h-3.5" />
          <span>Weather Prediction Reimagined</span>
        </div>
        
        <h1 className="text-4xl sm:text-6xl font-extrabold tracking-tight text-white leading-tight">
          AI-Powered Weather <br />
          <span className="bg-gradient-to-r from-sky-400 via-blue-500 to-purple-500 bg-clip-text text-transparent">
            Predictions & Chat
          </span>
        </h1>
        
        <p className="text-slate-300 text-base sm:text-lg max-w-2xl mx-auto leading-relaxed">
          Welcome to <span className="font-semibold text-white">SkyMind AI Weather</span>. 
          A premium SaaS platform providing hyper-local forecasting, real-time air quality tracking, 
          and conversational recommendations to safeguard your travel, health, and farming.
        </p>

        <div className="flex flex-wrap items-center justify-center gap-4 pt-4">
          <Link
            href={user ? "/dashboard" : "/login"}
            className="flex items-center gap-2 bg-gradient-to-r from-sky-500 to-blue-600 hover:from-sky-600 hover:to-blue-700 text-white font-semibold px-6 py-3 rounded-xl transition-all shadow-lg shadow-sky-500/15 group"
          >
            <span>{user ? "Enter Dashboard" : "Get Started Now"}</span>
            <ArrowRight className="w-4.5 h-4.5 group-hover:translate-x-1 transition-transform" />
          </Link>
          
          {!user && (
            <Link
              href="/login"
              className="flex items-center gap-2 bg-white/5 hover:bg-white/10 text-slate-200 hover:text-white border border-white/10 font-semibold px-6 py-3 rounded-xl transition-all"
            >
              <span>Login to Account</span>
            </Link>
          )}
        </div>
      </div>

      {/* Feature Section Grid */}
      <div className="mt-20 sm:mt-32 max-w-5xl px-4 w-full">
        <div className="text-center space-y-2 mb-12">
          <h2 className="text-2xl sm:text-3xl font-bold text-white">Advanced Platform Capabilities</h2>
          <p className="text-sm text-slate-400">Discover how SkyMind integrates deep intelligence with real-time forecasting</p>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
          {features.map((feature, idx) => (
            <div
              key={idx}
              className="group p-6 rounded-2xl border border-white/5 bg-slate-900/40 backdrop-blur-md hover:bg-slate-900/60 transition-all duration-300 hover:scale-[1.02] flex flex-col justify-between"
            >
              <div>
                <div className={`w-10 h-10 rounded-xl bg-gradient-to-br ${feature.color} flex items-center justify-center text-white mb-4 shadow-md group-hover:scale-110 transition-transform duration-300`}>
                  <feature.icon className="w-5 h-5" />
                </div>
                <h3 className="text-lg font-bold text-white mb-2">{feature.title}</h3>
                <p className="text-sm text-slate-400 leading-relaxed">{feature.desc}</p>
              </div>
            </div>
          ))}
        </div>
      </div>

      {/* Small Quote Banner */}
      {user && (
        <div className="mt-16 p-4 rounded-xl border border-sky-500/10 bg-sky-500/5 max-w-md text-center flex items-center gap-2 text-xs text-sky-300">
          <UserCheck className="w-4 h-4 shrink-0" />
          <span>You are currently signed in. Quick access available via the navigation tabs.</span>
        </div>
      )}
    </div>
  );
}
